// <auto-generated />
using System;
using EntityFramework;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace KiemDinhCongToP1.Migrations
{
    [DbContext(typeof(DBconnect))]
    [Migration("20201124025229_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("EntityFramework.Tem_Chi.DM_Chi", b =>
                {
                    b.Property<long>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .UseIdentityColumn();

                    b.Property<string>("Loai_Chi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ma_Chi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NguoiCapNhat")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("TGian_CapNhat")
                        .HasColumnType("datetime2");

                    b.HasKey("id");

                    b.ToTable("DM_Chis");
                });

            modelBuilder.Entity("EntityFramework.Tem_Chi.DM_DayChi", b =>
                {
                    b.Property<long>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .UseIdentityColumn();

                    b.Property<string>("Loai_DayChi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ma_DayChi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NguoiCapNhat")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("TGian_CapNhat")
                        .HasColumnType("datetime2");

                    b.HasKey("id");

                    b.ToTable("DM_DayChis");
                });

            modelBuilder.Entity("EntityFramework.Tem_Chi.DM_Tem", b =>
                {
                    b.Property<long>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .UseIdentityColumn();

                    b.Property<string>("Loai_Tem")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ma_Tem")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NguoiCapNhat")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("TGian_CapNhat")
                        .HasColumnType("datetime2");

                    b.HasKey("id");

                    b.ToTable("DM_Tems");
                });

            modelBuilder.Entity("EntityFramework.Tem_Chi.DangKy_TemChi", b =>
                {
                    b.Property<long>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .UseIdentityColumn();

                    b.Property<int?>("CapDuyet")
                        .HasColumnType("int");

                    b.Property<long?>("Id_NguoiDuyet")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("NgayCapNhat")
                        .HasColumnType("datetime2");

                    b.Property<string>("NguoiCapNhat")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("SoLuong_Dky")
                        .HasColumnType("int");

                    b.Property<string>("Ten_DKy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ThoiGianDuyet")
                        .HasColumnType("datetime2");

                    b.Property<int?>("TrangThaiDuyet")
                        .HasColumnType("int");

                    b.Property<long?>("id_NguoiDKy")
                        .HasColumnType("bigint");

                    b.Property<int?>("nam")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("Id_NguoiDuyet");

                    b.ToTable("DangKy_TemChis");
                });

            modelBuilder.Entity("EntityFramework.Tem_Chi.KDV_Chi", b =>
                {
                    b.Property<long>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .UseIdentityColumn();

                    b.Property<long?>("Chi_ID")
                        .HasColumnType("bigint");

                    b.Property<long?>("KDV_ID")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("Ngay_Su_Dung")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NguoiCapNhat")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("SoLuongChi")
                        .HasColumnType("int");

                    b.Property<int?>("SoLuongChi_Huy")
                        .HasColumnType("int");

                    b.Property<DateTime>("TGian_CapNhat")
                        .HasColumnType("datetime2");

                    b.HasKey("id");

                    b.HasIndex("Chi_ID");

                    b.HasIndex("KDV_ID");

                    b.ToTable("KDV_Chis");
                });

            modelBuilder.Entity("EntityFramework.Tem_Chi.KDV_DayChi", b =>
                {
                    b.Property<long>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .UseIdentityColumn();

                    b.Property<long?>("Daychi_ID")
                        .HasColumnType("bigint");

                    b.Property<long?>("KDV_ID")
                        .HasColumnType("bigint");

                    b.Property<string>("LoaiDayChi_Huy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("Ngay_Su_Dung")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NguoiCapNhat")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("SoLuong")
                        .HasColumnType("int");

                    b.Property<int?>("SoLuongDayChi")
                        .HasColumnType("int");

                    b.Property<int?>("SoLuongDayChi_Huy")
                        .HasColumnType("int");

                    b.Property<int?>("SoLuong_Huy")
                        .HasColumnType("int");

                    b.Property<DateTime>("TGian_CapNhat")
                        .HasColumnType("datetime2");

                    b.HasKey("id");

                    b.HasIndex("Daychi_ID");

                    b.HasIndex("KDV_ID");

                    b.ToTable("KDV_DayChis");
                });

            modelBuilder.Entity("EntityFramework.Tem_Chi.KDV_Tem", b =>
                {
                    b.Property<long>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .UseIdentityColumn();

                    b.Property<long?>("KDV_ID")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("Ngay_Su_Dung")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NguoiCapNhat")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Seri_Cuoi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Seri_Dau")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Seri_Tem_Huy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("SoLuong")
                        .HasColumnType("int");

                    b.Property<int?>("SoLuongTem")
                        .HasColumnType("int");

                    b.Property<int?>("SoLuongTem_Huy")
                        .HasColumnType("int");

                    b.Property<int?>("SoLuong_Huy")
                        .HasColumnType("int");

                    b.Property<DateTime>("TGian_CapNhat")
                        .HasColumnType("datetime2");

                    b.Property<long?>("Tem_ID")
                        .HasColumnType("bigint");

                    b.HasKey("id");

                    b.HasIndex("KDV_ID");

                    b.HasIndex("Tem_ID");

                    b.ToTable("KDV_Tems");
                });

            modelBuilder.Entity("EntityFramework.Tem_Chi.NQL_Chi", b =>
                {
                    b.Property<long>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .UseIdentityColumn();

                    b.Property<long?>("Chi_ID")
                        .HasColumnType("bigint");

                    b.Property<long?>("KDV_ID")
                        .HasColumnType("bigint");

                    b.Property<long?>("NQL_ID")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("Ngay_Cap_Phat")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NguoiCapNhat")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("SoLuong")
                        .HasColumnType("int");

                    b.Property<DateTime>("TGian_CapNhat")
                        .HasColumnType("datetime2");

                    b.HasKey("id");

                    b.HasIndex("Chi_ID");

                    b.HasIndex("KDV_ID");

                    b.ToTable("NQL_Chis");
                });

            modelBuilder.Entity("EntityFramework.Tem_Chi.NQL_DayChi", b =>
                {
                    b.Property<long>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .UseIdentityColumn();

                    b.Property<long?>("Daychi_ID")
                        .HasColumnType("bigint");

                    b.Property<long?>("KDV_ID")
                        .HasColumnType("bigint");

                    b.Property<long?>("NQL_ID")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("Ngay_Cap_Phat")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NguoiCapNhat")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("SoLuong")
                        .HasColumnType("int");

                    b.Property<DateTime>("TGian_CapNhat")
                        .HasColumnType("datetime2");

                    b.HasKey("id");

                    b.HasIndex("Daychi_ID");

                    b.HasIndex("KDV_ID");

                    b.ToTable("NQL_DayChis");
                });

            modelBuilder.Entity("EntityFramework.Tem_Chi.NQL_Tem", b =>
                {
                    b.Property<long>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .UseIdentityColumn();

                    b.Property<long?>("KDV_ID")
                        .HasColumnType("bigint");

                    b.Property<long?>("NQL_ID")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("Ngay_Cap_Phat")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NguoiCapNhat")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Seri_Cuoi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Seri_Dau")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("SoLuong")
                        .HasColumnType("int");

                    b.Property<DateTime>("TGian_CapNhat")
                        .HasColumnType("datetime2");

                    b.Property<long?>("Tem_ID")
                        .HasColumnType("bigint");

                    b.HasKey("id");

                    b.HasIndex("KDV_ID");

                    b.HasIndex("Tem_ID");

                    b.ToTable("NQL_Tems");
                });

            modelBuilder.Entity("EntityFramework.Tem_Chi.QL_CaiDat_CTDienTu", b =>
                {
                    b.Property<long>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .UseIdentityColumn();

                    b.Property<string>("DienLuc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GhiChu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("KDV_ID")
                        .HasColumnType("bigint");

                    b.Property<string>("MaCongTo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MaKim")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("Ngay_Cai")
                        .HasColumnType("datetimeoffset");

                    b.Property<long?>("NguoiCai")
                        .HasColumnType("bigint");

                    b.Property<int?>("SoLanCai")
                        .HasColumnType("int");

                    b.Property<string>("SoTem")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("TaiKhoansid")
                        .HasColumnType("bigint");

                    b.HasKey("id");

                    b.HasIndex("NguoiCai");

                    b.HasIndex("TaiKhoansid");

                    b.ToTable("QL_CaiDat_CTDienTus");
                });

            modelBuilder.Entity("EntityFramework.Tem_Chi.SLT_Chi", b =>
                {
                    b.Property<long>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .UseIdentityColumn();

                    b.Property<long?>("Chi_ID")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("Ngay_Cap_Phat")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NguoiCapNhat")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("SoLuongChi")
                        .HasColumnType("int");

                    b.Property<int?>("SoLuongChi_Huy")
                        .HasColumnType("int");

                    b.Property<int?>("SoLuongChi_Ton")
                        .HasColumnType("int");

                    b.Property<DateTime>("TGian_CapNhat")
                        .HasColumnType("datetime2");

                    b.HasKey("id");

                    b.HasIndex("Chi_ID");

                    b.ToTable("SLT_Chis");
                });

            modelBuilder.Entity("EntityFramework.Tem_Chi.SLT_DayChi", b =>
                {
                    b.Property<long>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .UseIdentityColumn();

                    b.Property<long?>("Daychi_ID")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("Ngay_Cap_Phat")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NguoiCapNhat")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("SoLuongDayChi")
                        .HasColumnType("int");

                    b.Property<int?>("SoLuongDayChi_Huy")
                        .HasColumnType("int");

                    b.Property<int?>("SoLuongDayChi_Ton")
                        .HasColumnType("int");

                    b.Property<DateTime>("TGian_CapNhat")
                        .HasColumnType("datetime2");

                    b.HasKey("id");

                    b.HasIndex("Daychi_ID");

                    b.ToTable("SLT_DayChis");
                });

            modelBuilder.Entity("EntityFramework.Tem_Chi.SLT_Tem", b =>
                {
                    b.Property<long>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .UseIdentityColumn();

                    b.Property<DateTimeOffset>("Ngay_Cap_Phat")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NguoiCapNhat")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("SoLuongTem")
                        .HasColumnType("int");

                    b.Property<int?>("SoLuongTem_Huy")
                        .HasColumnType("int");

                    b.Property<int?>("SoLuongTem_Ton")
                        .HasColumnType("int");

                    b.Property<DateTime>("TGian_CapNhat")
                        .HasColumnType("datetime2");

                    b.Property<long?>("Tem_ID")
                        .HasColumnType("bigint");

                    b.HasKey("id");

                    b.HasIndex("Tem_ID");

                    b.ToTable("SLT_Tems");
                });

            modelBuilder.Entity("EntityFramework.Tem_Chi.TaiKhoan", b =>
                {
                    b.Property<long>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .UseIdentityColumn();

                    b.Property<string>("CMIS_User_ID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("LaQuanLy")
                        .HasColumnType("int");

                    b.Property<string>("MaKDV")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MatKhau")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NguoiCapNhat")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("TGian_CapNhat")
                        .HasColumnType("datetime2");

                    b.Property<string>("TenDangNhap")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenDayDu")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("TaiKhoans");
                });

            modelBuilder.Entity("EntityFramework.Tem_Chi.DangKy_TemChi", b =>
                {
                    b.HasOne("EntityFramework.Tem_Chi.TaiKhoan", "TaiKhoan")
                        .WithMany("DangKy_TemChis")
                        .HasForeignKey("Id_NguoiDuyet")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("TaiKhoan");
                });

            modelBuilder.Entity("EntityFramework.Tem_Chi.KDV_Chi", b =>
                {
                    b.HasOne("EntityFramework.Tem_Chi.DM_Chi", "DM_Chi")
                        .WithMany("KDV_Chis")
                        .HasForeignKey("Chi_ID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("EntityFramework.Tem_Chi.TaiKhoan", "TaiKhoan")
                        .WithMany("KDV_Chis")
                        .HasForeignKey("KDV_ID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("DM_Chi");

                    b.Navigation("TaiKhoan");
                });

            modelBuilder.Entity("EntityFramework.Tem_Chi.KDV_DayChi", b =>
                {
                    b.HasOne("EntityFramework.Tem_Chi.DM_DayChi", "DM_DayChi")
                        .WithMany("KDV_DayChis")
                        .HasForeignKey("Daychi_ID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("EntityFramework.Tem_Chi.TaiKhoan", "TaiKhoan")
                        .WithMany("KDV_DayChis")
                        .HasForeignKey("KDV_ID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("DM_DayChi");

                    b.Navigation("TaiKhoan");
                });

            modelBuilder.Entity("EntityFramework.Tem_Chi.KDV_Tem", b =>
                {
                    b.HasOne("EntityFramework.Tem_Chi.TaiKhoan", "TaiKhoan")
                        .WithMany("KDV_Tems")
                        .HasForeignKey("KDV_ID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("EntityFramework.Tem_Chi.DM_Tem", "DM_Tem")
                        .WithMany("KDV_Tems")
                        .HasForeignKey("Tem_ID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("DM_Tem");

                    b.Navigation("TaiKhoan");
                });

            modelBuilder.Entity("EntityFramework.Tem_Chi.NQL_Chi", b =>
                {
                    b.HasOne("EntityFramework.Tem_Chi.DM_Chi", "DM_Chi")
                        .WithMany("NQL_Chis")
                        .HasForeignKey("Chi_ID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("EntityFramework.Tem_Chi.TaiKhoan", "TaiKhoan")
                        .WithMany("NQL_Chis")
                        .HasForeignKey("KDV_ID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("DM_Chi");

                    b.Navigation("TaiKhoan");
                });

            modelBuilder.Entity("EntityFramework.Tem_Chi.NQL_DayChi", b =>
                {
                    b.HasOne("EntityFramework.Tem_Chi.DM_DayChi", "DM_DayChi")
                        .WithMany("NQL_DayChis")
                        .HasForeignKey("Daychi_ID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("EntityFramework.Tem_Chi.TaiKhoan", "TaiKhoan")
                        .WithMany("NQL_DayChis")
                        .HasForeignKey("KDV_ID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("DM_DayChi");

                    b.Navigation("TaiKhoan");
                });

            modelBuilder.Entity("EntityFramework.Tem_Chi.NQL_Tem", b =>
                {
                    b.HasOne("EntityFramework.Tem_Chi.TaiKhoan", "TaiKhoan")
                        .WithMany("NQL_Tems")
                        .HasForeignKey("KDV_ID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("EntityFramework.Tem_Chi.DM_Tem", "DM_Tem")
                        .WithMany("NQL_Tems")
                        .HasForeignKey("Tem_ID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("DM_Tem");

                    b.Navigation("TaiKhoan");
                });

            modelBuilder.Entity("EntityFramework.Tem_Chi.QL_CaiDat_CTDienTu", b =>
                {
                    b.HasOne("EntityFramework.Tem_Chi.TaiKhoan", "TaiKhoan")
                        .WithMany("QL_CaiDat_CTDienTus")
                        .HasForeignKey("NguoiCai")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("EntityFramework.Tem_Chi.TaiKhoan", "TaiKhoans")
                        .WithMany()
                        .HasForeignKey("TaiKhoansid");

                    b.Navigation("TaiKhoan");

                    b.Navigation("TaiKhoans");
                });

            modelBuilder.Entity("EntityFramework.Tem_Chi.SLT_Chi", b =>
                {
                    b.HasOne("EntityFramework.Tem_Chi.DM_Chi", "DM_Chi")
                        .WithMany("SLT_Chis")
                        .HasForeignKey("Chi_ID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("DM_Chi");
                });

            modelBuilder.Entity("EntityFramework.Tem_Chi.SLT_DayChi", b =>
                {
                    b.HasOne("EntityFramework.Tem_Chi.DM_DayChi", "DM_DayChi")
                        .WithMany("SLT_DayChis")
                        .HasForeignKey("Daychi_ID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("DM_DayChi");
                });

            modelBuilder.Entity("EntityFramework.Tem_Chi.SLT_Tem", b =>
                {
                    b.HasOne("EntityFramework.Tem_Chi.DM_Tem", "DM_Tem")
                        .WithMany("SLT_Tems")
                        .HasForeignKey("Tem_ID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("DM_Tem");
                });

            modelBuilder.Entity("EntityFramework.Tem_Chi.DM_Chi", b =>
                {
                    b.Navigation("KDV_Chis");

                    b.Navigation("NQL_Chis");

                    b.Navigation("SLT_Chis");
                });

            modelBuilder.Entity("EntityFramework.Tem_Chi.DM_DayChi", b =>
                {
                    b.Navigation("KDV_DayChis");

                    b.Navigation("NQL_DayChis");

                    b.Navigation("SLT_DayChis");
                });

            modelBuilder.Entity("EntityFramework.Tem_Chi.DM_Tem", b =>
                {
                    b.Navigation("KDV_Tems");

                    b.Navigation("NQL_Tems");

                    b.Navigation("SLT_Tems");
                });

            modelBuilder.Entity("EntityFramework.Tem_Chi.TaiKhoan", b =>
                {
                    b.Navigation("DangKy_TemChis");

                    b.Navigation("KDV_Chis");

                    b.Navigation("KDV_DayChis");

                    b.Navigation("KDV_Tems");

                    b.Navigation("NQL_Chis");

                    b.Navigation("NQL_DayChis");

                    b.Navigation("NQL_Tems");

                    b.Navigation("QL_CaiDat_CTDienTus");
                });
#pragma warning restore 612, 618
        }
    }
}
